### ISSUE TITLE
rename the repo?

### ISSUE THREAD

**Issue by AriaMoradi** [AntiMicroX/antimicrox.github.io#2]
should we rename the repo?

my suggestions:
- website
- AntimicroX website
- AntimicroX.domain if we're ever going to buy one?

**Comment by pktiuk** [comment]
It is already hosted by github: https://antimicrox.github.io/

**Comment by pktiuk** [comment]
That's  why it is named in this way.

https://pages.github.com/

**Comment by AriaMoradi** [comment]
I know, but it does not look clean.

**Comment by pktiuk** [comment]
> I know, but it does not look clean.

It could be also said about our name of flatpak package `io.github.antimicrox.antimicrox` ;)

I think an effort needed to set up everything properly without using standard GitHub mechanisms of for websites is not worth it.

Btw current repository name resembles one of proposed names `AntimicroX.domain`

**Comment by gombosg** [comment]
Yes, it's to get that fully qualified domain package name for flatpak.
IMO https://antimicrox.github.io/ is perfectly fine for a website name anyway.

**Comment by pktiuk** [comment]
I think this issue can be closed for now.
