### ISSUE TITLE
Fix problems with automatic deployment

### ISSUE THREAD

**Issue by AriaMoradi** [AntiMicroX/antimicrox.github.io#3]
1- I made a deploy.sh script to test deployment and it pushes to `gh-pages`
2- github pages branch should be set to `gh-pages`
3- Also I copied a github actions script. It asks for a access token that should be set. @pktiuk

**Comment by pktiuk** [comment]
I have changed your role to maintainer and changed `gh-pages` to site branch

I think, that for tests you should rather try experimenting with your fork of this repo.   
It will make this repository cleaner.

**Comment by AriaMoradi** [comment]
once there's a basic scaffolding, we'll handle things by pull requests.

**Comment by AriaMoradi** [comment]
looks like it won't work without a access token

**Comment by pktiuk** [comment]
> Warning: Treat your tokens like passwords and keep them secret. When working with the API, use tokens as environment variables instead of hardcoding them into your programs.

How are we going to keep this token hidden?

**Comment by pktiuk** [comment]
I can't generate access token for organisation.

For now try to deal with everything on your fork, I will investigate possible solutions when I will have some time.

**Comment by AriaMoradi** [comment]
I'll build and push manually for now.

**Comment by AriaMoradi** [comment]
https://github.com/tachiyomiorg/website/blob/master/.github/workflows/push.yml can be used as a refrence. @pktiuk

**Comment by pktiuk** [comment]
According to [this](https://stackoverflow.com/questions/31159275/how-do-i-generate-the-github-oauth-token-for-organization-accounts) topic at  StackOverflow we as an organization are not able to generate required OAuth token required to deploying page.

I have found another organization which somehow managed to setup deploying pages https://github.com/xournalpp/xournalpp.github.io  We could ask them about it.

I will later investigate possible options later/

**Comment by jenkey2011** [comment]
Looks like you oauth token is not right;

### Create a personal access token

click your profile icon > Settings > Developer settings > Personal access tokens > Generate new token > At least check `repo`. Then you will get a token, copy it.


For more information: [https://help.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on](https://help.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on)

### Creating encrypted secrets

Under your repository name, click  Settings > Secrets > Type `ACCESS_TOKEN` in the "Name" input box && the the personal access token as value.

For more information: [https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)

**Comment by AriaMoradi** [comment]
Yes, It worked for me:
https://github.com/ArMor-Organaziaton/antimicrox-website/actions/runs/396014619
https://github.com/AriaMoradi/antimicrox.github.io/actions/runs/396014859

but if @pktiuk sets his personal access token and I add a commit, will it still work? or does it have to be my personal access token?

**Comment by AriaMoradi** [comment]
> Looks like you oauth token is not right;
> 
> ### Create a personal access token
> click your profile icon > Settings > Developer settings > Personal access tokens > Generate new token > At least check `repo`. Then you will get a token, copy it.
> 
> For more information: https://help.github.com/en/github/authenticating-to-github/authorizing-a-personal-access-token-for-use-with-saml-single-sign-on
> 
> ### Creating encrypted secrets
> Under your repository name, click Settings > Secrets > Type `ACCESS_TOKEN` in the "Name" input box && the the personal access token as value.
> 
> For more information: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets

@jenkey2011 thanks for the help, I think you should add this you your repo's README, also mention which permissions they should enable for the token.

**Comment by pktiuk** [comment]
I could create a new GitHub account, add it to this repository and use its token as a secret to push these changes. 

> but if @pktiuk sets his personal access token and I add a commit, will it still work? or does it have to be my personal access token?

I think it would work in this case.
